/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
* https://openapi-generator.tech
* Do not edit the class manually.
*
* Code generation script: src/main/openapi-generator/generate-marqeta-models.sh
*/
package com.luee.wally.api.tangocard.client.model;

import java.io.Serializable;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonProperty;
            
/**
 * AccountView
 */


public class AccountView  implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("accountIdentifier")
    private String accountIdentifier;
    @JsonProperty("accountNumber")
    private String accountNumber;
    @JsonProperty("contactEmail")
    private String contactEmail;
    @JsonProperty("createdAt")
    private String createdAt;
    @JsonProperty("currencyCode")
    private String currencyCode;
    @JsonProperty("currentBalance")
    private BigDecimal currentBalance;
    @JsonProperty("displayName")
    private String displayName;
    @JsonProperty("status")
    private String status;
    
    public AccountView() {
	
	}
	public String getAccountIdentifier() {
		return accountIdentifier;
	}
	public void setAccountIdentifier(String accountIdentifier) {
		this.accountIdentifier = accountIdentifier;
	}
	public String getAccountNumber() {
		return accountNumber;
	}
	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}
	public String getContactEmail() {
		return contactEmail;
	}
	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}
	public String getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}
	public String getCurrencyCode() {
		return currencyCode;
	}
	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}
	public BigDecimal getCurrentBalance() {
		return currentBalance;
	}
	public void setCurrentBalance(BigDecimal currentBalance) {
		this.currentBalance = currentBalance;
	}
	public String getDisplayName() {
		return displayName;
	}
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
    
    
}

