/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
* https://openapi-generator.tech
* Do not edit the class manually.
*
* Code generation script: src/main/openapi-generator/generate-marqeta-models.sh
*/
package com.luee.wally.api.tangocard.client.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;


            
/**
 * OrderListItemView
 */


public class OrderListItemView  implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("accountIdentifier")
    private String accountIdentifier;
    @JsonProperty("accountNumber")
    private String accountNumber;
    @JsonProperty("amountCharged")
    private MoneyView amountCharged;
    @JsonProperty("campaign")
    private String campaign;
    @JsonProperty("createdAt")
    private String createdAt;
    @JsonProperty("customerIdentifier")
    private String customerIdentifier;
    @JsonProperty("denomination")
    private MoneyView denomination;
    @JsonProperty("emailSubject")
    private String emailSubject;
    @JsonProperty("etid")
    private String etid;
    @JsonProperty("externalRefID")
    private String externalRefID;
    @JsonProperty("message")
    private String message;
    @JsonProperty("notes")
    private String notes;
    @JsonProperty("recipient")
    private RecipientInfoView recipient;
    @JsonProperty("referenceOrderID")
    private String referenceOrderID;
    @JsonProperty("rewardName")
    private String rewardName;
    @JsonProperty("sendEmail")
    private Boolean sendEmail;
    @JsonProperty("sender")
    private SenderInfoView sender;
    @JsonProperty("status")
    private String status;
    @JsonProperty("utid")
    private String utid;
    
    public OrderListItemView() {
	
	}
    
    public RecipientInfoView getRecipient() {
		return recipient;
	}
    public void setRecipient(RecipientInfoView recipient) {
    	this.recipient = recipient;
    }
    public SenderInfoView getSender() {
		return sender;
	}
    public void setSender(SenderInfoView sender) {
		this.sender = sender;
	}
	public String getAccountIdentifier() {
		return accountIdentifier;
	}

	public void setAccountIdentifier(String accountIdentifier) {
		this.accountIdentifier = accountIdentifier;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public MoneyView getAmountCharged() {
		return amountCharged;
	}

	public void setAmountCharged(MoneyView amountCharged) {
		this.amountCharged = amountCharged;
	}

	public String getCampaign() {
		return campaign;
	}

	public void setCampaign(String campaign) {
		this.campaign = campaign;
	}

	public String getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	public String getCustomerIdentifier() {
		return customerIdentifier;
	}

	public void setCustomerIdentifier(String customerIdentifier) {
		this.customerIdentifier = customerIdentifier;
	}

	public MoneyView getDenomination() {
		return denomination;
	}

	public void setDenomination(MoneyView denomination) {
		this.denomination = denomination;
	}

	public String getEmailSubject() {
		return emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	public String getEtid() {
		return etid;
	}

	public void setEtid(String etid) {
		this.etid = etid;
	}

	public String getExternalRefID() {
		return externalRefID;
	}

	public void setExternalRefID(String externalRefID) {
		this.externalRefID = externalRefID;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getReferenceOrderID() {
		return referenceOrderID;
	}

	public void setReferenceOrderID(String referenceOrderID) {
		this.referenceOrderID = referenceOrderID;
	}

	public String getRewardName() {
		return rewardName;
	}

	public void setRewardName(String rewardName) {
		this.rewardName = rewardName;
	}

	public Boolean getSendEmail() {
		return sendEmail;
	}

	public void setSendEmail(Boolean sendEmail) {
		this.sendEmail = sendEmail;
	}


	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getUtid() {
		return utid;
	}

	public void setUtid(String utid) {
		this.utid = utid;
	}
    
    
    
}

