/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
* https://openapi-generator.tech
* Do not edit the class manually.
*
* Code generation script: src/main/openapi-generator/generate-marqeta-models.sh
*/
package com.luee.wally.api.tangocard.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;


            
/**
 * OrderListView
 */

public class OrderListView  implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("orders")
    private List<OrderListItemView> orders = new ArrayList<>();
    
    @JsonProperty("page")
    private PageView page;

    public OrderListView() {
	
	}
    
	public PageView getPage() {
		return page;
	}

	public void setPage(PageView page) {
		this.page = page;
	}

	public List<OrderListItemView> getOrders() {
		return orders;
	}

	public void setOrders(List<OrderListItemView> orders) {
		this.orders = orders;
	}
    
	
	
    
}

