/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
* https://openapi-generator.tech
* Do not edit the class manually.
*
* Code generation script: src/main/openapi-generator/generate-marqeta-models.sh
*/
package com.luee.wally.api.tangocard.client.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;
            
/**
 * RecipientInfoView
 */


public class RecipientInfoView  implements Serializable {
    private static final long serialVersionUID = 1L;

    @JsonProperty("email")
    private String email;
    @JsonProperty("firstName")
    private String firstName;
    @JsonProperty("lastName")
    private String lastName;
    
    public RecipientInfoView() {
	
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
    
    
}

