package com.luee.wally.csv;

import java.math.BigDecimal;


public class UserLevelRevenue {

	private String AdUnitID; // ID of the MAX ad unit from which the revenue was
								// generated.
	private String IDFA; // Advertising identifier: IDFA for iOS devices, GAID
							// for Android devices.
	private String IDFV; // Identifier for vendor. Only set on iOS devices.
	private String UserID; // Optional ID of the user set via Applovin SDK (see
							// the ‘Setting Internal User ID’ section below)
	private int Impressions; // The number of ads displayed to the user.
	private BigDecimal Revenue; // The revenue generated by the user in USD,
								// expressed with 6 decimal percisiton
	public String getAdUnitID() {
		return AdUnitID;
	}
	public void setAdUnitID(String adUnitID) {
		AdUnitID = adUnitID;
	}
	public String getIDFA() {
		return IDFA;
	}
	public void setIDFA(String iDFA) {
		IDFA = iDFA;
	}
	public String getIDFV() {
		return IDFV;
	}
	public void setIDFV(String iDFV) {
		IDFV = iDFV;
	}
	public String getUserID() {
		return UserID;
	}
	public void setUserID(String userID) {
		UserID = userID;
	}
	public int getImpressions() {
		return Impressions;
	}
	public void setImpressions(int impressions) {
		Impressions = impressions;
	}
	public BigDecimal getRevenue() {
		return Revenue;
	}
	public void setRevenue(BigDecimal revenue) {
		Revenue = revenue;
	}

}
